// Mock data for BraxTech.net - A fictional tech company

export const BRAXTECH_COMPANY = {
  name: "BraxTech",
  domain: "braxtech.net",
  tagline: "Innovative Software Solutions",
  description: "BraxTech is a leading software development company specializing in AI-powered enterprise solutions, cloud infrastructure, and digital transformation services.",
  primaryColor: "#6366F1",
  secondaryColor: "#8B5CF6",
};

// Mock Businesses
export const mockBusinesses = [
  {
    id: "mock-business-1",
    name: "BraxTech Solutions",
    description: "Enterprise software development and consulting",
    logo_url: null,
    primary_color: "#6366F1",
    team_id: "mock-team-1",
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Brands
export const mockBrands = [
  {
    id: "mock-brand-1",
    name: "BraxCloud",
    description: "Cloud infrastructure and DevOps solutions",
    logo_url: null,
    primary_color: "#0EA5E9",
    secondary_color: "#38BDF8",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    parent_id: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-brand-2",
    name: "BraxAI",
    description: "Artificial intelligence and machine learning products",
    logo_url: null,
    primary_color: "#8B5CF6",
    secondary_color: "#A78BFA",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    parent_id: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-brand-3",
    name: "BraxSecure",
    description: "Cybersecurity and compliance solutions",
    logo_url: null,
    primary_color: "#10B981",
    secondary_color: "#34D399",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    parent_id: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Campaigns
export const mockCampaigns = [
  {
    id: "mock-campaign-1",
    name: "BraxCloud Launch 2026",
    description: "Major product launch campaign for BraxCloud 3.0 featuring new AI-powered infrastructure management and multi-cloud orchestration.",
    status: "active" as const,
    brand_id: "mock-brand-1",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    start_date: new Date().toISOString().split('T')[0],
    end_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    budget: 150000,
    currency: "USD",
    tags: ["product-launch", "cloud", "enterprise"],
    goals: [
      { type: "leads", target: 5000, description: "Generate qualified leads" },
      { type: "signups", target: 1000, description: "Free trial signups" },
    ],
    cover_image_url: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-campaign-2",
    name: "AI Innovation Summit",
    description: "Annual tech conference showcasing BraxAI's latest developments in generative AI, LLM integration, and enterprise AI adoption.",
    status: "in_review" as const,
    brand_id: "mock-brand-2",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    start_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 33 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    budget: 250000,
    currency: "USD",
    tags: ["conference", "AI", "thought-leadership"],
    goals: [
      { type: "attendees", target: 2000, description: "Conference attendees" },
      { type: "partnerships", target: 10, description: "New partnerships" },
    ],
    cover_image_url: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-campaign-3",
    name: "Security Awareness Month",
    description: "Educational campaign promoting cybersecurity best practices and BraxSecure's enterprise security solutions.",
    status: "approved" as const,
    brand_id: "mock-brand-3",
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 44 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    budget: 75000,
    currency: "USD",
    tags: ["security", "education", "awareness"],
    goals: [
      { type: "downloads", target: 10000, description: "Whitepaper downloads" },
      { type: "webinar_attendees", target: 500, description: "Webinar attendees" },
    ],
    cover_image_url: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-campaign-4",
    name: "Q1 Partner Program",
    description: "Channel partner recruitment and enablement campaign to expand BraxTech's global partner network.",
    status: "draft" as const,
    brand_id: null,
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    start_date: null,
    end_date: null,
    budget: 100000,
    currency: "USD",
    tags: ["partners", "channel", "growth"],
    goals: [],
    cover_image_url: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-campaign-5",
    name: "Customer Success Stories",
    description: "Showcase of enterprise customer implementations and success stories featuring Fortune 500 companies.",
    status: "completed" as const,
    brand_id: null,
    business_id: "mock-business-1",
    team_id: "mock-team-1",
    start_date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    budget: 50000,
    currency: "USD",
    tags: ["case-studies", "customer-success", "enterprise"],
    goals: [
      { type: "case_studies", target: 12, description: "Published case studies" },
    ],
    cover_image_url: null,
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Assets
export const mockAssets = [
  {
    id: "mock-asset-1",
    name: "BraxCloud Logo Primary",
    description: "Primary logo for BraxCloud brand",
    file_url: "/placeholder.svg",
    file_type: "image/svg+xml",
    file_size: 24576,
    thumbnail_url: "/placeholder.svg",
    asset_type: "brand_asset" as const,
    status: "approved" as const,
    brand_id: "mock-brand-1",
    team_id: "mock-team-1",
    folder_id: null,
    current_version: 1,
    metadata: { format: "SVG", dimensions: "512x512" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-asset-2",
    name: "AI Summit Hero Banner",
    description: "Main hero banner for AI Innovation Summit",
    file_url: "/placeholder.svg",
    file_type: "image/png",
    file_size: 2457600,
    thumbnail_url: "/placeholder.svg",
    asset_type: "image" as const,
    status: "approved" as const,
    brand_id: "mock-brand-2",
    team_id: "mock-team-1",
    folder_id: null,
    current_version: 3,
    metadata: { format: "PNG", dimensions: "1920x1080" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-asset-3",
    name: "Security Infographic",
    description: "Cybersecurity best practices infographic",
    file_url: "/placeholder.svg",
    file_type: "image/png",
    file_size: 1843200,
    thumbnail_url: "/placeholder.svg",
    asset_type: "image" as const,
    status: "pending_review" as const,
    brand_id: "mock-brand-3",
    team_id: "mock-team-1",
    folder_id: null,
    current_version: 1,
    metadata: { format: "PNG", dimensions: "1080x2400" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-asset-4",
    name: "BraxTech Icon Set",
    description: "Unified icon set for all BraxTech products",
    file_url: "/placeholder.svg",
    file_type: "image/svg+xml",
    file_size: 102400,
    thumbnail_url: "/placeholder.svg",
    asset_type: "icon" as const,
    status: "approved" as const,
    brand_id: null,
    team_id: "mock-team-1",
    folder_id: null,
    current_version: 2,
    metadata: { format: "SVG", icons: 48 },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-asset-5",
    name: "Product Demo Video Thumbnail",
    description: "Thumbnail for BraxCloud product demo",
    file_url: "/placeholder.svg",
    file_type: "image/jpeg",
    file_size: 512000,
    thumbnail_url: "/placeholder.svg",
    asset_type: "image" as const,
    status: "approved" as const,
    brand_id: "mock-brand-1",
    team_id: "mock-team-1",
    folder_id: null,
    current_version: 1,
    metadata: { format: "JPEG", dimensions: "1280x720" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Mock Collections
export const mockCollections = [
  {
    id: "mock-collection-1",
    name: "BraxCloud Launch Assets",
    description: "All marketing assets for the BraxCloud 3.0 launch campaign",
    is_public: false,
    cover_image_url: null,
    brand_id: "mock-brand-1",
    business_id: "mock-business-1",
    campaign_id: "mock-campaign-1",
    team_id: "mock-team-1",
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    asset_count: 24,
    brand: { id: "mock-brand-1", name: "BraxCloud" },
    business: { id: "mock-business-1", name: "BraxTech Solutions" },
    campaign: { id: "mock-campaign-1", name: "BraxCloud Launch 2026" },
  },
  {
    id: "mock-collection-2",
    name: "AI Summit 2026 Materials",
    description: "Conference branding, signage, and promotional materials",
    is_public: false,
    cover_image_url: null,
    brand_id: "mock-brand-2",
    business_id: "mock-business-1",
    campaign_id: "mock-campaign-2",
    team_id: "mock-team-1",
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    asset_count: 18,
    brand: { id: "mock-brand-2", name: "BraxAI" },
    business: { id: "mock-business-1", name: "BraxTech Solutions" },
    campaign: { id: "mock-campaign-2", name: "AI Innovation Summit" },
  },
  {
    id: "mock-collection-3",
    name: "Brand Guidelines",
    description: "Official BraxTech brand guidelines and assets",
    is_public: true,
    cover_image_url: null,
    brand_id: null,
    business_id: "mock-business-1",
    campaign_id: null,
    team_id: "mock-team-1",
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    asset_count: 45,
    brand: null,
    business: { id: "mock-business-1", name: "BraxTech Solutions" },
    campaign: null,
  },
  {
    id: "mock-collection-4",
    name: "Security Awareness Content",
    description: "Educational materials and infographics for security campaign",
    is_public: false,
    cover_image_url: null,
    brand_id: "mock-brand-3",
    business_id: "mock-business-1",
    campaign_id: "mock-campaign-3",
    team_id: "mock-team-1",
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    asset_count: 12,
    brand: { id: "mock-brand-3", name: "BraxSecure" },
    business: { id: "mock-business-1", name: "BraxTech Solutions" },
    campaign: { id: "mock-campaign-3", name: "Security Awareness Month" },
  },
];

// Mock Campaign Posts
export const mockCampaignPosts = [
  {
    id: "mock-post-1",
    title: "BraxCloud 3.0 Launch Announcement",
    content: "🚀 Introducing BraxCloud 3.0 - The future of cloud infrastructure is here! Our new AI-powered platform reduces deployment times by 70% and cuts costs by 40%.\n\nKey features:\n✅ Auto-scaling with ML predictions\n✅ Multi-cloud orchestration\n✅ Zero-downtime migrations\n\nStart your free trial today! #BraxCloud #CloudComputing #Innovation",
    campaign_id: "mock-campaign-1",
    team_id: "mock-team-1",
    platforms: ["linkedin", "twitter", "facebook"] as const,
    status: "scheduled" as const,
    hashtags: ["BraxCloud", "CloudComputing", "Innovation", "Enterprise"],
    mentions: ["@braxtech"],
    media_urls: [],
    link_url: "https://braxtech.net/braxcloud",
    notes: "Main launch post - coordinate with PR team",
    platform_variants: {},
    utm_params: { source: "social", medium: "organic", campaign: "braxcloud-launch" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    post_schedules: [
      {
        id: "mock-schedule-1",
        post_id: "mock-post-1",
        platform: "linkedin" as const,
        scheduled_for: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: "America/New_York",
        published_at: null,
        external_post_id: null,
        publish_error: null,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "mock-post-2",
    title: "AI Summit Early Bird Registration",
    content: "🎯 AI Innovation Summit 2026 - Early bird tickets now available!\n\nJoin 2,000+ tech leaders for 3 days of:\n• Keynotes from AI pioneers\n• Hands-on workshops\n• Networking with industry leaders\n\nSave 30% with code EARLY2026\n\n#AIInnovation #TechConference #BraxAI",
    campaign_id: "mock-campaign-2",
    team_id: "mock-team-1",
    platforms: ["linkedin", "twitter"] as const,
    status: "approved" as const,
    hashtags: ["AIInnovation", "TechConference", "BraxAI"],
    mentions: [],
    media_urls: [],
    link_url: "https://braxtech.net/ai-summit",
    notes: null,
    platform_variants: {},
    utm_params: { source: "social", medium: "organic", campaign: "ai-summit-2026" },
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    post_schedules: [],
  },
  {
    id: "mock-post-3",
    title: "Cybersecurity Tip #1",
    content: "🔐 Security Tip: Enable Multi-Factor Authentication (MFA) everywhere!\n\n87% of breaches could be prevented with MFA. It takes just 5 minutes to set up and provides an extra layer of protection.\n\nLearn more in our free security guide ⬇️\n\n#CyberSecurity #InfoSec #BraxSecure",
    campaign_id: "mock-campaign-3",
    team_id: "mock-team-1",
    platforms: ["linkedin", "twitter", "facebook"] as const,
    status: "draft" as const,
    hashtags: ["CyberSecurity", "InfoSec", "BraxSecure"],
    mentions: [],
    media_urls: [],
    link_url: "https://braxtech.net/security-guide",
    notes: "Part of weekly security tips series",
    platform_variants: {},
    utm_params: {},
    created_by: "mock-user-1",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    post_schedules: [],
  },
];

// Mock Dashboard Stats
export const mockDashboardStats = {
  totalAssets: 156,
  totalCollections: 12,
  teamMembers: 8,
  totalDownloads: 2847,
  totalBusinesses: 1,
  totalBrands: 3,
  totalCampaigns: 5,
  activeCampaigns: 1,
  scheduledPosts: 12,
  figmaConnected: true,
};

// Mock Recent Assets for Dashboard
export const mockRecentAssets = [
  { id: "mock-asset-3", name: "Security Infographic", asset_type: "image", created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "mock-asset-5", name: "Product Demo Thumbnail", asset_type: "image", created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "mock-asset-2", name: "AI Summit Hero Banner", asset_type: "image", created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "mock-asset-1", name: "BraxCloud Logo Primary", asset_type: "brand_asset", created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: "mock-asset-4", name: "BraxTech Icon Set", asset_type: "icon", created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString() },
];

// Mock Recent Campaigns for Dashboard
export const mockRecentCampaigns = [
  { id: "mock-campaign-4", name: "Q1 Partner Program", status: "draft" as const, start_date: null, end_date: null },
  { id: "mock-campaign-3", name: "Security Awareness Month", status: "approved" as const, start_date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], end_date: new Date(Date.now() + 44 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] },
  { id: "mock-campaign-2", name: "AI Innovation Summit", status: "in_review" as const, start_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], end_date: new Date(Date.now() + 33 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] },
  { id: "mock-campaign-1", name: "BraxCloud Launch 2026", status: "active" as const, start_date: new Date().toISOString().split('T')[0], end_date: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] },
  { id: "mock-campaign-5", name: "Customer Success Stories", status: "completed" as const, start_date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], end_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0] },
];

// Mock Upcoming Posts for Dashboard
export const mockUpcomingPosts = [
  {
    id: "mock-schedule-1",
    title: "BraxCloud 3.0 Launch Announcement",
    content: "🚀 Introducing BraxCloud 3.0...",
    scheduled_for: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    platform: "linkedin" as const,
    campaign_name: "BraxCloud Launch 2026",
  },
  {
    id: "mock-schedule-2",
    title: "BraxCloud 3.0 Launch Announcement",
    content: "🚀 Introducing BraxCloud 3.0...",
    scheduled_for: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 3600000).toISOString(),
    platform: "twitter" as const,
    campaign_name: "BraxCloud Launch 2026",
  },
  {
    id: "mock-schedule-3",
    title: "Weekly AI Insights",
    content: "This week in AI: Top developments...",
    scheduled_for: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    platform: "linkedin" as const,
    campaign_name: "AI Innovation Summit",
  },
];

// Mock Activity Feed
export const mockActivity = [
  {
    id: "mock-activity-1",
    action: "created",
    entity_type: "campaign",
    entity_id: "mock-campaign-4",
    metadata: { name: "Q1 Partner Program" },
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    user_id: "mock-user-1",
    team_id: "mock-team-1",
    profile: { full_name: "Alex Chen", email: "alex@braxtech.net" },
  },
  {
    id: "mock-activity-2",
    action: "uploaded",
    entity_type: "asset",
    entity_id: "mock-asset-3",
    metadata: { name: "Security Infographic" },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    user_id: "mock-user-2",
    team_id: "mock-team-1",
    profile: { full_name: "Sarah Miller", email: "sarah@braxtech.net" },
  },
  {
    id: "mock-activity-3",
    action: "approved",
    entity_type: "campaign",
    entity_id: "mock-campaign-3",
    metadata: { name: "Security Awareness Month" },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    user_id: "mock-user-1",
    team_id: "mock-team-1",
    profile: { full_name: "Alex Chen", email: "alex@braxtech.net" },
  },
  {
    id: "mock-activity-4",
    action: "updated",
    entity_type: "asset",
    entity_id: "mock-asset-2",
    metadata: { name: "AI Summit Hero Banner" },
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    user_id: "mock-user-3",
    team_id: "mock-team-1",
    profile: { full_name: "Jordan Lee", email: "jordan@braxtech.net" },
  },
  {
    id: "mock-activity-5",
    action: "created",
    entity_type: "collection",
    entity_id: "mock-collection-4",
    metadata: { name: "Security Awareness Content" },
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    user_id: "mock-user-2",
    team_id: "mock-team-1",
    profile: { full_name: "Sarah Miller", email: "sarah@braxtech.net" },
  },
];

// Mock Team Members
export const mockTeamMembers = [
  {
    id: "mock-member-1",
    user_id: "mock-user-1",
    team_id: "mock-team-1",
    role: "admin" as const,
    joined_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    invited_by: null,
    profile: { full_name: "Alex Chen", email: "alex@braxtech.net", avatar_url: null },
  },
  {
    id: "mock-member-2",
    user_id: "mock-user-2",
    team_id: "mock-team-1",
    role: "editor" as const,
    joined_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    invited_by: "mock-user-1",
    profile: { full_name: "Sarah Miller", email: "sarah@braxtech.net", avatar_url: null },
  },
  {
    id: "mock-member-3",
    user_id: "mock-user-3",
    team_id: "mock-team-1",
    role: "editor" as const,
    joined_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    invited_by: "mock-user-1",
    profile: { full_name: "Jordan Lee", email: "jordan@braxtech.net", avatar_url: null },
  },
  {
    id: "mock-member-4",
    user_id: "mock-user-4",
    team_id: "mock-team-1",
    role: "viewer" as const,
    joined_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    invited_by: "mock-user-1",
    profile: { full_name: "Taylor Swift", email: "taylor@braxtech.net", avatar_url: null },
  },
];

// Mock Canvas Items for Business Canvas
export const mockCanvasItems = {
  key_partners: [
    { id: "mock-canvas-1", content: "**AWS** - Primary cloud infrastructure partner", color: "blue" },
    { id: "mock-canvas-2", content: "**Microsoft Azure** - Enterprise integrations", color: "purple" },
    { id: "mock-canvas-3", content: "**NVIDIA** - AI/ML hardware partnerships", color: "green" },
  ],
  key_activities: [
    { id: "mock-canvas-4", content: "Software development and R&D", color: "yellow" },
    { id: "mock-canvas-5", content: "Customer success and onboarding", color: "orange" },
    { id: "mock-canvas-6", content: "Enterprise sales and partnerships", color: "pink" },
  ],
  value_propositions: [
    { id: "mock-canvas-7", content: "## AI-Powered Automation\nReduce operational costs by 40% with intelligent automation", color: "green" },
    { id: "mock-canvas-8", content: "## Multi-Cloud Flexibility\nDeploy anywhere without vendor lock-in", color: "blue" },
  ],
  customer_segments: [
    { id: "mock-canvas-9", content: "**Enterprise** - Fortune 500 companies", color: "purple" },
    { id: "mock-canvas-10", content: "**Mid-Market** - Growing tech companies", color: "blue" },
    { id: "mock-canvas-11", content: "**Startups** - High-growth tech startups", color: "green" },
  ],
  channels: [
    { id: "mock-canvas-12", content: "Direct sales team", color: "yellow" },
    { id: "mock-canvas-13", content: "Partner network and resellers", color: "orange" },
    { id: "mock-canvas-14", content: "Self-service platform (braxtech.net)", color: "pink" },
  ],
  customer_relationships: [
    { id: "mock-canvas-15", content: "Dedicated account managers for enterprise", color: "blue" },
    { id: "mock-canvas-16", content: "24/7 technical support", color: "green" },
  ],
  key_resources: [
    { id: "mock-canvas-17", content: "Engineering team (150+ developers)", color: "purple" },
    { id: "mock-canvas-18", content: "Proprietary AI/ML models", color: "blue" },
    { id: "mock-canvas-19", content: "Global cloud infrastructure", color: "green" },
  ],
  cost_structure: [
    { id: "mock-canvas-20", content: "Engineering and R&D (45%)", color: "orange" },
    { id: "mock-canvas-21", content: "Cloud infrastructure costs (25%)", color: "yellow" },
    { id: "mock-canvas-22", content: "Sales and marketing (20%)", color: "pink" },
  ],
  revenue_streams: [
    { id: "mock-canvas-23", content: "**SaaS subscriptions** - Monthly/annual plans", color: "green" },
    { id: "mock-canvas-24", content: "**Enterprise licenses** - Custom agreements", color: "blue" },
    { id: "mock-canvas-25", content: "**Professional services** - Implementation & training", color: "purple" },
  ],
  challenges: [
    { id: "mock-canvas-26", content: "Intense competition from hyperscalers (AWS, GCP, Azure)", color: "orange" },
    { id: "mock-canvas-27", content: "Talent acquisition in competitive AI market", color: "yellow" },
  ],
  competitors: [
    { id: "mock-canvas-28", content: "**Datadog** - Observability and monitoring", color: "purple" },
    { id: "mock-canvas-29", content: "**HashiCorp** - Infrastructure automation", color: "blue" },
  ],
  innovation: [
    { id: "mock-canvas-30", content: "AI-powered predictive infrastructure scaling", color: "green" },
    { id: "mock-canvas-31", content: "Natural language infrastructure management", color: "blue" },
  ],
  unique_selling_point: [
    { id: "mock-canvas-32", content: "**Only** platform combining AI automation with true multi-cloud portability", color: "purple" },
  ],
  corporate_structure: [
    { id: "mock-canvas-33", content: "C-Suite → VPs → Directors → Engineering Teams", color: "blue" },
    { id: "mock-canvas-34", content: "3 business units: Cloud, AI, Security", color: "green" },
  ],
  solution: [
    { id: "mock-canvas-35", content: "Unified platform for cloud infrastructure management with AI-driven optimization", color: "green" },
  ],
  impact: [
    { id: "mock-canvas-36", content: "Customers report **40% cost reduction** on average", color: "purple" },
    { id: "mock-canvas-37", content: "**70% faster** deployment times", color: "blue" },
  ],
  success_metrics: [
    { id: "mock-canvas-38", content: "ARR: $50M target for 2026", color: "green" },
    { id: "mock-canvas-39", content: "NPS: 65+ score", color: "blue" },
    { id: "mock-canvas-40", content: "Customer retention: 95%+", color: "purple" },
  ],
};
